sudo: required
services:
  - docker

before_install:
  - docker build -t dylansyj/docker-multi -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dylansyj/docker-multi npm test -- --coverage

after_success:
  - docker build -t dylansyj/multi-nginx ./nginx
  - docker build -t dylansyj/multi-server ./server
  - docker build -t dylansyj/multi-worker ./worker
  - docker build -t dylansyj/multi-client ./client
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker ps -a
  - docker push dylansyj/multi-nginx
  - docker push dylansyj/multi-server
  - docker push dylansyj/multi-worker
  - docker push dylansyj/multi-client

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-205944129820"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY